
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: cheers_mail_development

test:
  <<: *default
  database: cheers_mail_test

production:
  <<: *default
  database: cheers_mail_production
  username: cheers_mail
  password: <%= ENV['CHEERS_MAIL_DATABASE_PASSWORD'] %>
